### PR TITLE
chore/fix-author

### PR DESCRIPTION
**Pull request by billyxs**

### CODE REVIEW

**Comment by billyxs** [comment]
Fixing some commits with my work email with a git-extras `reauthor`

**Comment by seesleestak** [comment]
Is this intended to consolidate your author name in the history? I think I’m seeing a couple variants in the log still

**Comment by seesleestak** [comment]
```
$ git shortlog -se | sort
   114  Billy Montgomery <billy.montgomery@gmail.com>
    15  billyxs <billy.montgomery@gmail.com>
    35  Billy <billy.montgomery@gmail.com>
    82  Calvin Cieslak <calvin.cieslak@gmail.com>
     8  Billy Montgomery <billym@yelp.com>
```

**Comment by seesleestak** [comment]
The shortlog looks good now, I think. But where did the changed files come from?

**Comment by billyxs** [comment]
> The shortlog looks good now, I think. But where did the changed files come from?

Yeah, normalizing along the way. I've tried this a few different ways, and it's a product of the rebase and change in history. If you are able to do it without having the changes, happy to see that branch :)

**Comment by seesleestak** [comment]
Tried it with a script for `git filter-branch` like [this](https://www.git-tower.com/learn/git/faq/change-author-name-email) article described, but ended up with the changed files all the same. Suppose it can't be avoided.

Although, I'm seeing a small discrepancy in the commit numbers between our branches.
On `chore/fix-author`:
```
$ git shortlog -se | sort
    42  Calvin Cieslak <calvin.cieslak@gmail.com>
    91  Billy Montgomery <billy.montgomery@gmail.com>
```

On `chore/billy-reauthor`:
```
$ git shortlog -se | sort
    46  Calvin Cieslak <calvin.cieslak@gmail.com>
    91  Billy Montgomery <billy.montgomery@gmail.com>
```

**Comment by billyxs** [comment]
haha, I saw that article. That's pretty much what `git reauthor` does https://github.com/tj/git-extras/blob/master/bin/git-reauthor#L43

Reran the reauthor...looks correct

**Pull request merged**
